# This workflow runs for every push to main
name: Push CI

on:
  push:
    branches:
      - main    

jobs:
  push-ci-verification:
    uses: .github/workflows/library_dafny_verification.yml
    with:
      dafny: 'nightly-2023-07-18-8657ef9'
  push-ci-java:
    uses: .github/workflows/library_java_tests.yml
    with:
      dafny: 'nightly-2023-07-18-8657ef9'
  push-ci-net:
    uses: .github/workflows/library_net_tests.yml
    with:
      dafny: 'nightly-2023-07-18-8657ef9'
